### PR TITLE
add versioned golang.mk

### PR DESCRIPTION
**Pull request by natebrennand**

### CODE REVIEW

**Comment by natebrennand** [comment]
@rgarcia / @kvigen: can we publicly archive this?
(I don't really want to figure out the broken tests for something we don't use anymore)

**Comment by rgarcia** [comment]
I can move to graveyard

**Comment by natebrennand** [comment]
KV pointed out there's a chance people are using it. Should we move to "ARCHIVE-..." for a month or two first?

**Comment by rgarcia** [comment]
sounds good, done

**Pull request closed without merging**
